### PR TITLE
[9.0] connector cmis enhancement

### PR DESCRIPTION
**Pull request by lmignon**
This PR is based on #9 
### The rationale

These changes aims to provide the basis to develop new Odoo models linked to a specific content into a CMIS container.
For example, it's a common need to manage in a unified way a claim and all the documents related to the claim. By default, odoo let's you attach document to a claim but doesn't provide all the functionalities required to efficiently manage these documents (versioning, metadata, content indexation, typing, rendering, editorial process management, ...). All these requirements are already provided by some externals tools as Alfresco, Nuxeo, ...
### The results

Thanks to the functionalities provided by this PR, you can extend the `crm.claim` model to link one claim to a folder in a cmis container as simple as writing

``` python
from openerp import models


class CrmClaim(models.Model):
    _name = 'crm.claim'
    _inherit = ['crm.claim', 'cmis.folder']

```

A new widget will allow you to display the content of a cmis:folder linked to a claim. To use this new widget you should override the intial form as follow.

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<odoo>
    <data>

        <record id="crm_case_claims_form_view" model="ir.ui.view">
            <field name="name">CRM - Claims Form (cmis_crm_claim)</field>
            <field name="model">crm.claim</field>
            <field name="inherit_id" ref="crm_claim.crm_case_claims_form_view"/>
            <field name="arch" type="xml">
                <notebook position="inside">
                    <page string="Documents" groups="base.group_user">
                        <field name="cmis_objectid" readonly="1" widget="cmis_viewer"/>
                        <field name="cmis_backend_id" readonly="1" invisible="1"/>
                    </page>
                </notebook>
            </field>
        </record>   
    </data>

</odoo>
```

image

And you are now able to see all the documents related to the claim on the claim itself, and do all your work into odoo even if your documents are stored into a cmis container

https://www.youtube.com/watch?v=TK49kl0Viyk

As already announced, the widget will be published on OCA and is compatible Odoo community/entreprise.

### CODE REVIEW

**Comment by raditv** [comment]
Where is the cmis_viewer widget location?

**Comment by sbidoul** [comment]
@raditv cmis_viewer is not yet released. We plan to release it during Odoo Experience early october. Note that a major refactoring of this branch is underway, so don't rely on it.

**Comment by lmignon** [comment]
@raditv The cmis_viewer widget is not yet released. We work hard to release a version as soon as possible (before the odoo experience) but we have decided to refactor and simplify the code in the next days because we want to be sure to provide a clean API before releasing this new addon.
The Idea is to replace the required base model in the current implementation by a new specialized field and register the widget as the default one for this new kind of field.

``` python
from openerp import models
from openerp.addons.cmis import fields

class CrmClaim(models.Model):
    _inherit = 'crm.claim'

    my_cmis_folder = fields.CmisFolder(.....)
```

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<odoo>
        <record id="crm_case_claims_form_view" model="ir.ui.view">
            <field name="name">CRM - Claims Form (cmis_crm_claim)</field>
            <field name="model">crm.claim</field>
            <field name="inherit_id" ref="crm_claim.crm_case_claims_form_view"/>
            <field name="arch" type="xml">
                <notebook position="inside">
                    <page string="Documents" groups="base.group_user">
                        <field name="my_cmis_folder"/>
                    </page>
                </notebook>
            </field>
        </record>   
</odoo>
```

**Comment by raditv** [comment]
I see, thank you for fast response because I thought it's done already.

**Comment by lmignon** [comment]
superseded by #16

**Pull request closed without merging**
